### ISSUE TITLE
Alignment

### ISSUE THREAD

**Issue by Gawie-Schneider** [tommueller/ng-mat-search-bar#6] opened 2019-05-20 20:22 UTC
Hi there,

I did as you mentioned, however the component keeps aligning left and opening toward the left side.

The component was added as part of a div element, so nothing funny there. It doesn't want to stretch either.

Please advise

Angular 7 btw

**Comment by tommueller** [comment] 2019-05-21 08:32
Hi @Gawie-Schneider,
if I understand you correctly, it works as intended. The input is supposed to overlay content next to it. It is absolutly positioned. So you would need to make sure that it is positioned correctly.
If that is not what you meant, please provide a stackblitz to illustrate the issue.
Best!

**Comment by tommueller** [comment] 2019-06-06 10:09
I will close this as you did not reply any more. Cheers

**Closed as completed by tommueller** 2019-06-06 10:09 UTC
