### ISSUE TITLE
onClose event is not working

### ISSUE THREAD

**Issue by asku3000** [tommueller/ng-mat-search-bar#17] opened 2019-06-26 15:09 UTC
When i am on normal screen of my chrome it doesn;t fire up the onClose event when i close the bar.
But when i press F12 and do the same then it is firing up that event
<img width="893" alt="afterPressingCross" src="https://user-images.githubusercontent.com/30684146/60191726-6c1b9d00-9852-11e9-9cee-cc36fa64d767.PNG">
<img width="907" alt="onF12" src="https://user-images.githubusercontent.com/30684146/60191740-7178e780-9852-11e9-9b73-221bf522a3e6.PNG">

**Comment by tommueller** [comment] 2019-09-13 08:15
I need more information on this. `onClose`-event is only triggered when you actually click the close-button. If you close by clicking somewhere else on the page `onBlur`-event is fired instead.
I cannot reproduce the issue so far, so maybe it is a confusion on that behalf?
Cheers

**Comment by ray-man** [comment] 2019-09-18 11:46
`onClose` event not firing for me too, even at clicking cross button.

**Comment by tommueller** [comment] 2019-09-18 11:48
As I said, please provide a repro, otherwise I cannot help with this. Works fine for me.

**Comment by ray-man** [comment] 2019-09-18 11:50
This seem like an error cause by css or element misplacement, temporary workaround for me is handle `onClose` and `onBlur` both events with same function.

**Comment by quedicesebas** [comment] 2019-12-20 18:43
Had to set onClose and onBlur as @ray-man suggested, but is not an ideal solution.

**Comment by tommueller** [comment] 2020-01-06 08:55
I still cannot reproduce this. Is this maybe specific to some OS or browser?

**Comment by tommueller** [comment] 2020-07-01 14:09
Closing because of missing repro.

**Closed as completed by tommueller** 2020-07-01 14:09 UTC
